# Generated by Django 6.0.3 on 2026-04-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
